### ISSUE TITLE
Proposed PBS-Java default account config change

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server-java#1151]
As a follow up https://github.com/prebid/prebid-server/pull/1426, we plan to change the default account configuration syntax.

Having the overall default account config in JSON simplifies mapping it to the `Account` object since it can be unmarshalled directly from JSON.

Instead of current the YAML format like this:
```yaml
settings:  
  default-account-config:
    events-enabled: true
    enforce-ccpa: true
    gdpr: '{"enabled": true}'
    analytics-sampling-factor: 1
    default-integration: pbjs
    analytics-config: '{"auction-events":{"amp":true}}'
```

we'd like to use JSON format for `default-account-config` section:
```yaml
settings:  
  default-account-config: >
    {
      "eventsEnabled": true,
      "enforceCcpa": true,
      "gdpr": {
        "enabled": true
      },
      "analyticsSamplingFactor": 1,
      "defaultIntegration": "pbjs"
    }
```

The PR is  https://github.com/prebid/prebid-server-java/pull/1142
