### ISSUE TITLE
Stored Requests by account id for filesystem

### ISSUE THREAD

**Issue by muuki88** [prebid/prebid-server-java#1179]
In #488 stored request by account id where introduced, but as far as I understand this doesn't cover the `filesystem` stored requests implementation. Currently the configuration looks like this

```yaml
settings:
  filesystem:
    stored-requests-dir: configs/stored-requests
```

A simple solution would be something like this

```yaml
settings:
  filesystem:
    stored-requests-dir: configs/stored-requests
    appendAccountId: true
```

this wouldeffectively appending the `accountId` to the path. If a request has the accountId _example.com_
it would turn `configs/stored-requests` into `configs/stored-requests/example.com`.

## FileApplicationSettings

https://github.com/prebid/prebid-server-java/blob/a44b7001dfa4d6918789108436e8c2a3a16a6623/src/main/java/org/prebid/server/settings/FileApplicationSettings.java#L42-L44

## Related

Relates to https://github.com/prebid/prebid-server/issues/1024
