### ISSUE TITLE
Cache server circuit breaker

### ISSUE THREAD

**Issue by dzesm** [prebid/prebid-server-java#3216]
Hello.

What would be the best way to configure the circuit breaker for cache? 

This is what we have:

``` 
circuitbreaker:
  failure_rate_threshold: 50
  open_state_duration: 60000
  closed_state_calls_number: 5
  half_open_state_calls_number: 3 
```

But, we are getting the following error:

``` 
{\"error\":\"Internal Server Error\",\"status\":500,\"path\":\"/cache\",\"message\":\"CircuitBreaker 'prebid-cache-repository-circuit-breaker' is OPEN and does not permit further calls\",\"timestamp\":1716979781967} 
```

One of the suggestions I found is this: "Ensure that the number of successful calls exceeds the closed_state_calls_number threshold to reset the circuit breaker back to the CLOSED state." 
And we have an error rate above 50% up to 100%.

Do you know what is wrong with this configuration?
Thanks for your help.
